TRACK_KEYWORDS = {
    "ml": [
        "machine learning",
        "machine-learning",
        "mlops",
        "deep learning",
        "tensorflow",
        "pytorch",
        "scikit",
        "data scientist",
        "model",
        "nlp",
    ],
    "cloud": [
        "aws",
        "azure",
        "gcp",
        "kubernetes",
        "docker",
        "terraform",
        "cloud",
        "devops",
        "infrastructure",
    ],
    "dev": [
        "backend",
        "api",
        "python",
        "java",
        "node",
        "software engineer",
        "full-stack",
        "frontend",
    ],
}
